id: arduino:keyword_spotting
name: Keyword Spotting
description: |
  Brick for keyword spotting using a pre-trained model. It processes audio input to detect specific keywords or phrases.
  Brick is designed to work with pre-trained models provided by framework or with custom audio classification models trained on Edge Impulse platform.
category: audio
required_devices:
  - microphone
requires_container: true
requires_model: true
model: keyword-spotting-hey-arduino
model_configuration_variables:
  - EI_KEYWORD_SPOTTING_MODEL
