id: arduino:cloud_llm
name: Cloud LLM
description: "Cloud LLM Brick enables seamless integration with cloud-based Large Language Models (LLMs) for advanced AI capabilities in your Arduino projects."
disabled: true

variables:
  - API_KEY