name: Detect speech from microphone, event stream
icon: 🎙️
description: "Detect speech from microphone, event stream. Requires an USB microphone connected to the Arduino board."

bricks:
  - arduino:cloud_asr
