services:
  llamacpp-models-runner:
    image: ${DOCKER_REGISTRY_BASE:-ghcr.io/arduino/}app-bricks/llamacpp-runner:dev-next
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    environment:
      - LLAMA_LOG_LEVEL=error
      - LLAMA_ARG_CTX_SIZE=${X_LLAMA_ARG_CTX_SIZE:-1024}
      - LLAMA_ARG_REASONING=${X_LLAMA_ARG_REASONING:-off}
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=9999
      - LLAMA_ARG_MODELS_DIR=/models
      - LLAMA_ARG_MODELS_MAX=${X_LLAMA_ARG_MODELS_MAX:-4}
      - LLAMA_ARG_BATCH=${X_LLAMA_ARG_BATCH:-2048}
      - LLAMA_ARG_UBATCH=${X_LLAMA_ARG_UBATCH:-512}
      - LLAMA_ARG_MLOCK=${X_LLAMA_ARG_MLOCK:-1}
      - LLAMA_ARG_N_PREDICT=${X_LLAMA_ARG_N_PREDICT:-512}
      - XDG_CACHE_HOME=/models
      - LLAMA_ARG_THREADS=${X_LLAMA_ARG_THREADS:-8}
      - LLAMA_ARG_REASONING=${X_LLAMA_ARG_REASONING:-off}
      - LLAMA_ARG_THINK_BUDGET=${X_LLAMA_ARG_THINK_BUDGET:--1}
      - LLAMA_ARG_N_GPU_LAYERS=${X_LLAMA_ARG_N_GPU_LAYERS:-all}
      - LLAMA_ARG_N_PARALLEL=${X_LLAMA_ARG_N_PARALLEL:-1} # Force to 1 to avoid CPU fallback in Hexagon use case
      #- LLAMA_API_KEY=${X_LLAMA_API_KEY:-key}
    working_dir: /models
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:9999:9999
    mem_limit: 10g
    oom_kill_disable: false
    shm_size: 2g
    devices:
      - /dev/dma_heap/system
      - /dev/dma_heap/qcom,system
      - /dev/fastrpc-cdsp    
    volumes:
      - /var/lib/arduino-app-cli/models/llamacpp/:/models/