id: arduino:arduino_cloud
name: Arduino Cloud
description: "Connects to Arduino Cloud"
variables:
- name: ARDUINO_DEVICE_ID
  description: Arduino Cloud Device ID
- name: ARDUINO_SECRET
  description: Arduino Cloud Secret