id: arduino:vlm
name: Vision Language Model (VLM)
description: "Vision Language Model (VLM) Brick enables seamless integration with locally hosted VLMs for advanced AI capabilities in your Arduino projects."
requires_services: ["arduino:genie"]
requires_model: true
model: genie:qwen2_5_vl_7b_instruct
supported_boards: ["ventunoq"]
ai_frameworks_compatibility:
  - genie
