name: Chat with a Local LLM using a specific model
icon: 🤖
description: "Chat with a Local LLM using a specific model. Models must be downloaded and available locally."

bricks:
  - arduino:llm:
    model: genie:qwen3_4b_instruct_2507
